### ISSUE TITLE
HTML Format of Pagination May Need an Update

### ISSUE THREAD

**Issue by dylan-k** [SimonPadbury/b4st#2]
It looks like, starting around line 41 of setup.php, the pagination function isn't outputting html that is structured in the same way as [the bootstrap 4 docs now suggest.](http://v4-alpha.getbootstrap.com/components/pagination/#disabled-and-active-states) Perhaps it's a recent change to Bootstrap 4?

(on the plus side, the function uses a more semantically appropriate chevron in place of the right angle quote.)

**Comment by SimonPadbury** [comment]
Thanks, Dylan. 

Yes, swapping in Bootstrap 4.0.0-alpha.2 for the previous alpha did 'break' my pagination. I've fixed that now.

**b4st** on here (GitHub repo) is now updated to 4.0.0-alpha.2 and the pagination has been updated accordingly.

**Comment by dylan-k** [comment]
This looks fixed, but would it also apply to paged posts?

**Comment by SimonPadbury** [comment]
Hi Dylan,

No, it doesn't apply to paged posts. 

But as you are interested in that, I have been working on it today. And so I have just now added in another function in `functions/setup.php` that does what you require: `b4st_wp_link_pages()`. 

Note: as I preferred to use icon links for "fastforward to last page" and "fastbackward to first page" within the paged posts pagination, I opted for Font Awesome icons `fa-angle-*` instead of `fa-chevron-*` (since there is no double chevron). And, to be consistent across the theme, I also switched to `fa-angle-*` in the index (and category) pagination.

Also, I bumped up the version number to **b4st 1.2** after these changes.

Simon
