### ISSUE TITLE
Two calls to bootstrap css

### ISSUE THREAD

**Issue by nicogaldo** [SimonPadbury/b4st#24]
Hello Simon, I have a question: 
In the file [`enqueues.php line 7`](https://github.com/SimonPadbury/b4st/blob/1f96157e21a2f9ee19fd69fa7d28ce5eccc17f65/functions/enqueues.php#L7) you make the call of the css of boostrap 4-beta, but in the [`editor-style.css line 9`](https://github.com/SimonPadbury/b4st/blob/1f96157e21a2f9ee19fd69fa7d28ce5eccc17f65/theme/css/editor-style.css#L9) file you also do it.

This is on purpose? I tried commenting on line 9 of the editor-style.css but all my design has been disarmed!

Thank you for creating this great starter theme!

**Comment by SimonPadbury** [comment]
Hi Nicogaldo,

You need to retain both.

1.  `enqueues.php` line 7 –– this puts Bootstrap 4 into the theme frontend.

2.  `editor-style.css` line 9 –– this puts Bootstap 4 into the WYSIWYG editor (backend), so that your blog writer can get an idea of what the frontend post will be. 

The WYSIWYG editor doesn't have Bootstrap grid-system classes, so the editor content width will not be the same as your article column width in the frontend. This is why I in my `README.md` I say WYSI(M!)WYG = what you see is (mostly!) what you get.

You see also, that I @import `b4st.css` into `editor-style.css`. If you have any important typographic styles that the blog writer must see, then I also recommend you create another CSS file for these and @import it into `editor-style.css`.

Enjoy! :-)

**Comment by nicogaldo** [comment]
Okay, now I understand!
Will you need to update the bootstrap url in the editor-style.css file? (no longer alpha)

**Comment by SimonPadbury** [comment]
Hi Nicolás,

Thankyou — it is now fixed.

:-)

Simon
