### ISSUE TITLE
Navbar two deep levels

### ISSUE THREAD

**Issue by estudio3551** [SimonPadbury/b4st#25]
Hi!. When a try to make a two deep levels in the navbar it's broken, and shows nothing.
Example of what I want to make:
**MENU
      --Level 1
              --Level 2**
This is not posible.
Only let me do this:
**MENU
      --Level 1**
Nothing shows.
![image](https://user-images.githubusercontent.com/15659907/31239523-bd305f92-a9d3-11e7-8e4e-bab04fdffef5.png)

**Comment by SimonPadbury** [comment]
Hello,

I just downloaded a fresh **b4st** from this repository, and I installed it on my local server (I am using AMPPS, from [https://www.ampps.com/](https://www.ampps.com/)). I set up some test menus in WordPress, and...

...it is all working OK for me. :-)

Can you check that your `bootstrap.min.js` is being obtained from the CDN? If the Bootstrap JavaScript is present, then whenever you click the navbar parent link, this should happen:

1. The parent `<li>` should be receiving another class " slow"
2. The parent `<a>` should be recieving `area-expanded="true"
3. The **dropdown** wrapper `<ul>` should also be receiving another class " slow"

Check these out using the **inspector** (in Firefox, Chrome, etc.). If all that above is OK, then the problem is not with b4st (or Bootstrap).

After that, check **your CSS**. Maybe something you added has prevented the dropdown appearance. Usually, something is affection the check the `display` and `position` rules on the dropdown and/or on the parent `<li>`.

If you can't solve the problem, then maybe you can send me your (unfinished) code or upload it to a dev/demo location for me to inspect.

**Comment by estudio3551** [comment]
Thanks for your quick response. I can't make it work, so I solved with a plugin. 
It's a great starter theme for my projects, thanks again.

**Comment by SimonPadbury** [comment]
Hi estudio, 

Maybe try this one more time:

Get a new b4st download from my GitHub repository. Install it on your WordPress and test it with your menu. It should work OK.

Then you will know it’s not me. :-)

Simon

**Comment by estudio3551** [comment]
I know it's not you. If I think that, I don't use your Starter Theme. It only shows

Only shows one level, I need two levels.
![image](https://user-images.githubusercontent.com/15659907/31279017-b939c16c-aa7d-11e7-8867-5a538edbbf58.png)

**Comment by SimonPadbury** [comment]
OK, I think I misunderstood:


Bootstrap ordinarily allows 2 levels:

Parent link
--------------
Child link 1
Child link 2
Child link 3

b4st also does this OK.

Are you asking for 3 levels?

Parent link
--------------
Child link 1
Child link 2 > Grandchild 2,1
Child link 3    Grandchild 2,2
                      Grandchild 2,3

……………………………………


You could do that:

(1.) Option 1:

1. `header.php` change to `depth => 3,`
2. And modify so that it _does not use my navwalker_.
3. And then in your CSS, configure the child and grandchild menus to appear on `li:hover` (you can copy Bootstrap CSS ideas but have it not powered by JS, only CSS hover).


(2.) Option 2: 

1. `header.php` change to `depth => 3,`
2. Use Bootstrap / b4st OK for the child menu
3. Copy one of these examples:

https://gist.github.com/mrogur/0a03d2f201e424c31d15829afcb53ae6 <https://gist.github.com/mrogur/0a03d2f201e424c31d15829afcb53ae6> 
https://codepen.io/svnt/pen/beEgre <https://codepen.io/svnt/pen/beEgre> 

These may be better for you than a plugin. Less clutter in your setup. No need to do update.

Whatever you do, remember to test it on a phone or tablet (because no hover). 

Simon

**Comment by estudio3551** [comment]
OK,. i'll try.
Thanks
