### ISSUE TITLE
Error when open category that doesn't has article

### ISSUE THREAD

**Issue by bossby** [SimonPadbury/b4st#26]
I get an error when i open a category that doesn't has article.  

![localerror](https://user-images.githubusercontent.com/21689649/31849893-32a6c264-b674-11e7-9356-1356245e0415.png)

I made a little change in Category.php to checking if there is a post in that article

		`	<?php get_template_part('loops/content', get_post_format()); ?>`

to 

```
   <?php if(have_posts()):?>
			<?php get_template_part('loops/content', get_post_format()); ?>
     	<?php endif;?>
```

well, maybe some one will face this. sorry for my bad english

**Comment by SimonPadbury** [comment]
Hello Boby 

I just saw your message. I will try to help later today. Of if I don’t get time, then Monday or early next week.

Simon

**Comment by SimonPadbury** [comment]
Hello Boby,

There is no problem with your code modification. It works OK:

```
<?php get_header(); ?>

<div class="container">
  <div class="row">
    
    <div class="<?php if(is_active_sidebar('sidebar-widget-area')): ?>col-sm-8<?php else: ?>col-sm-12<?php endif; ?>">
      <div id="content" role="main">
        <header>
          <h1>Category: <?php echo single_cat_title(); ?></h1>
          <hr>
        </header>
        
        <?php if(have_posts()): ?>
          <?php get_template_part('loops/content', get_post_format()); ?>
        <?php endif; ?>
        
      </div><!-- /#content -->
    </div>
    
    <div class="col-sm-4" id="sidebar" role="navigation">
       <?php get_sidebar(); ?>
    </div>
    
  </div><!-- /.row -->
</div><!-- /.container -->

<?php get_footer(); ?>
```

"Headers never sent" errors often (always?) happen because of an extra space after the last `?>` in your file. Maybe you did not add this extra white space – but your text-editor added it.

Read this:

[http://www.wpbeginner.com/wp-tutorials/how-to-fix-pluggable-php-file-errors-in-wordpress/](http://www.wpbeginner.com/wp-tutorials/how-to-fix-pluggable-php-file-errors-in-wordpress/)

[https://make.wordpress.org/support/handbook/appendix/breakfix-lessons/php-whitespace-headers-already-sent/](https://make.wordpress.org/support/handbook/appendix/breakfix-lessons/php-whitespace-headers-already-sent/)

[https://www.wpeka.com/how-to-fix-pluggable-php-file-errors-in-wordpress.html](https://www.wpeka.com/how-to-fix-pluggable-php-file-errors-in-wordpress.html)
 
Check every PHP that you modified.
