### ISSUE TITLE
Slick Slider

### ISSUE THREAD

**Issue by kaplan512** [SimonPadbury/b4st#31]
Hi again, Have you tested your theme with slick slider http://kenwheeler.github.io/slick/? 
I don't know why, but it looks totally broken...

**Comment by SimonPadbury** [comment]
Hi Kaplan,

So far I have some this OK -- this all works, except that I have not fixed the prev & next chevrons. The Slick font is not being discovered. But we're 99% done, because the JS is all working here:

(1.) Copy the `slick/` folder into the B4ST theme root folder.

(2.) Styles and scripts in `functions/enqueues.php` (note: Slick is recommending an older jQuery that what is used by Bootstrap 4 -- therefore don't use the newer jQuery -- Bootstrap 4 seems to be OK with this older jQuery):

```
/* SLICK Styles and Scripts */

wp_register_style('slick-css', get_template_directory_uri() . '/slick/slick.css', false, null);
wp_enqueue_style('slick-css');

wp_register_style('slick-theme-css', get_template_directory_uri() . '/slick/slick-theme.css', false, null);
wp_enqueue_style('slick-theme-css');

wp_register_script('jquery-2.2.0', 'https://code.jquery.com/jquery-2.2.0.min.js', false, '3.2.1', true);
wp_enqueue_script('jquery-2.2.0');

wp_register_script('slick-js', get_template_directory_uri() . '/slick/slick.js', false, null, true);
wp_enqueue_script('slick-js');

```

(3.) The other small Slick CSS `<style>` I copied into my `header.php`. 

(4.) **Slick initiation:** you need the other small Slick JS to be enqueued AFTER `slick.js` (and `slick-theme.js`). So, for testing purposes I simply copied this into my "document ready" function in `theme/js/b4st.js` (while putting the Slick styles and scripts earlier in the enqueues:

```
    $(".vertical-center-4").slick({
      dots: true,
      vertical: true,
      centerMode: true,
      slidesToShow: 4,
      slidesToScroll: 2
    });
    $(".vertical-center-3").slick({
      dots: true,
      vertical: true,
      centerMode: true,
      slidesToShow: 3,
      slidesToScroll: 3
    });
    $(".vertical-center-2").slick({
      dots: true,
      vertical: true,
      centerMode: true,
      slidesToShow: 2,
      slidesToScroll: 2
    });
    $(".vertical-center").slick({
      dots: true,
      vertical: true,
      centerMode: true,
    });
    $(".vertical").slick({
      dots: true,
      vertical: true,
      slidesToShow: 3,
      slidesToScroll: 3
    });
    $(".regular").slick({
      dots: true,
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 3
    });
    $(".center").slick({
      dots: true,
      infinite: true,
      centerMode: true,
      slidesToShow: 5,
      slidesToScroll: 3
    });
    $(".variable").slick({
      dots: true,
      infinite: true,
      variableWidth: true
    });
    $(".lazy").slick({
      lazyLoad: 'ondemand', // ondemand progressive anticipated
      infinite: true
    });
```

(4.) For testing purposes, I simply copied all the Slick `index.html` `<section>` demos into my theme `index.php`. You can try something more complicated, e.g. set up a custom post type, or shortcode.

***

I have to go now.

If you can finalise this by getting the prev & next button icons to appear, please let me know here.

**Comment by kaplan512** [comment]
Hello. I did slider but outside of .container .row, so outside of bootstrap grid. Otherway it is broken.
I use my custom prev & next button icons

**Comment by SimonPadbury** [comment]
Hi Kaplan,

I have now written a tutorial on how to add Slick to b4st.

https://github.com/SimonPadbury/b4st/wiki/How-to-add-Slick-Slider-to-b4st
