### ISSUE TITLE
how to edit scss and then compile it to css in wordpress

### ISSUE THREAD

**Issue by sslakd** [SimonPadbury/b4st#34]
Hi,
I'm new to bootstrap 4, when reading its documentation I can't get to the point how to edit scss and then compile it to css in wordpress. Can you help showing me step by step or give me a link tell me how I can do it ?

**Comment by SimonPadbury** [comment]
Hi Son,

OK. What do you use to compile SCSS?

Simon

**Comment by sslakd** [comment]
I would like to use [Koala ](http://koala-app.com/) for compiling. I search in your theme pack and found no scss file, you compiled it, right ?

**Comment by SimonPadbury** [comment]
Hi Son,

No I didn’t compile Bootstrap. b4st is getting it from the Cloudflare Content Delivery Network  (CDN): https://cdnjs.com/libraries/twitter-bootstrap 

It is also getting other things from there: jQuery, Popper, Modernizr and Font Awesome.

Koala is excellent. I like Koala and I also like Scout-App.

[1.] On the Bootstrap download page — http://getbootstrap.com/docs/4.0/getting-started/download/ — you need to click the button “Download source” to get everything.

[2.] Inside, there are many folders and files, but for SCSS you only need the folder `scss/` (and everything in it). Copy this folder into the theme (and rename it to `bootstrap-scss`, so that you have:

```
b4st/
│
├── theme/
│   ├── fontawesome/
│   ├── css/
│   ├── js/
│   └── bootstrap-scss/   <== from the Bootstrap source download
│
…And the other stuff.
```

[3.] If you will use B4ST, then you need to change it. in `functions/enqueues.php` it is linking to Bootstrap CSS and JS on a Content Delivery Network (CDN) called Cloudflare. If you are going to compile your own Bootstrap, then you need to:

1. Copy the downloaded `bootstrap.min.js` from the DIST folder to `b4st/theme/js/`
2. You also need Font Awesome — download it from https://fontawesome.com 
3. You also need jQuery and Popper (and maybe Modernizr, if you are supporting old browsers) — so find and get these too, and put them in `b4st/theme/js/`
4. Now modify `functions/enqueues.php` to link to YOUR `font-awesome.min.css` and all YOUR JS files in your theme
5. /* comment out */ the link to `bootstrap.min.js` — because you are going to combile Bootstrap SCSS into YOUR CSS.

[4.] In the theme stylesheet rename `b4st.css` ==> `b4st.scss`. and inside it, near the top, you need three SCSS @includes:

```
// YOUR BOOTSTRAP VARIABLE OVERRIDES GO HERE, FIRST, BEFORE BOOTSTRAP

@include "../bootstrap-scss/bootstrap-reboot.scss";
@include "../bootstrap-scss/bootstrap-grid";
@include "../bootstrap-scss/bootstrap.scss";

… your SCSS later…
```

[5.] Most of what you want to do with Bootstrap is override its variables, _to make your website not look so much like Bootstrap_. If you look at the Bootstrap SCSS file `_variables.scss` you will see that many of them have `!default`. This means that you can override them by declaring the same variables BEFORE BOOTSTRAP but with your choise of values.

[6.] If you are struggling with SCSS, then watch this video: 

https://www.youtube.com/watch?v=wz3kElLbEHE

**Comment by sslakd** [comment]
Wow,
Thanks for your detailing step.
However, I stuck at ```Now modify functions/enqueues.php to link to YOUR font-awesome.min.css and all YOUR JS files in your theme```. Can you help me out ?

**Comment by sslakd** [comment]
Also note that there is ```boostrap.min.css```, do I need to /* comment out */ also ?

**Comment by SimonPadbury** [comment]
> However, I stuck at Now modify functions/enqueues.php to link to YOUR font-awesome.min.css and all YOUR JS files in your theme. Can you help me out ?

Example: `enqueues.php` change this:

```
wp_register_script('jquery-3.2.1', 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js', false, '3.2.1', true);
wp_enqueue_script('jquery-3.2.1');
```

to become this:

```
wp_register_script('jquery-3.2.1', '../theme/js/jquery.min.js', false, '3.2.1', true);
wp_enqueue_script('jquery-3.2.1');
```

So, first you need to download all the JS files that you need (Bootstrap, jQuery, Popper, Modernizer) and put them inside `theme/js`

Then you need to change the enqueue link to those files, as in the example above.

Why do this? Because now you have all your assets within your theme, and so your theme will be ready for deployment.

(My b4st theme is a "starter" -- something for e.g. you to begin your work upon.

**Comment by SimonPadbury** [comment]
> Also note that there is boostrap.min.css, do I need to /* comment out */ also ?

Haha, my mistake. Sorry!

* DON'T /* comment out */ the link to `bootstrap.min.js` -- you need this (linking to YOUR downloaded `bootstrap.min.js`.

* DO /* comment out */ the link to `bootstrap.min.css` -- because you won't need it.

Instead, you will be compiling bootstrap INTO YOUR `b4st.css` -- using those `@include` things I had in step [4.].

So, this will happen: There will be one stylesheet* `b4st.css` that will contain Bootstrap (SCSS, compiled to CSS) plus your styles (SCSS, compiled to CSS).

---
[*Sorry, actually two stylesheets -- because you need the Font Awesome stylesheet also.]

---

When you do your designing, you will need to follow this process in your SCSS:

1. Override the Bootstrap variables (e.g. change the color of the primary button to whatever you prefer)
2. `@include` Bootstrap (maybe include all Bootstrap, or only those parts you really need)
3. Create your extra styles

All of 1+2+3 is getting compiled into one stylesheet `b4st.css` (You can rename it later).

Here is a tutorial that may help you. I have my own framework, called _Codebase_. Read this Codebase "Getting Started" documentation page -- to get ideas for that you need to do. But don't focus on Codebase -- you are using Bootstrap 4. (Also, Codebase doesn't use SCSS, it used indented-syntax Sass.) Read the whole "Getting Started" page -- but the parts that are relevant for you are beginning at "Advanced Setup".

http://simonpadbury.github.io/Codebase/getting-started.html

**Comment by sslakd** [comment]
Thanks a lot man. You are my savior 👍 .

**Comment by SimonPadbury** [comment]
Thankyou. But there is only one Savior.
