### ISSUE TITLE
Child theme for B4ST

### ISSUE THREAD

**Issue by danielmrey** [SimonPadbury/b4st#35]
Hi Simon:

I am going to test you B4ST... Exciting!

Just installed it, can you please let me know if you have a clean child theme for this B4ST?

Thank you!

**Comment by SimonPadbury** [comment]
Hi Daniel,

I don’t normally work off of a child theme for b4st — it is itself a starter theme. 

Instead of writing you an email explaining how to do it, I just wrote this tutorial and put it up there for all to see:

https://github.com/SimonPadbury/b4st/wiki/Creating-a-b4st-child-theme <https://github.com/SimonPadbury/b4st/wiki/Creating-a-b4st-child-theme>

Go for it.

Simon

**Comment by danielmrey** [comment]
Hi Simon:

I used the BST Child and changed the "Template: b4st-master" in the root CSS and it worked but I will use these instructions instead.

Shouldn't the name of the CSS in step 3 be: E.g. css/b4st_child.css ?

Thank you Simon

**Comment by SimonPadbury** [comment]
Yes, thanks.

Corrected.
