### ISSUE TITLE
Trouble adding post types

### ISSUE THREAD

**Issue by liammday** [SimonPadbury/b4st#36]
I can see that the functions.php enables multiple post types, and that the comment included in the content.php file explains how to create a different template file eg content-aside.php.

However when I do this by creating the above named file, I hit all kinds of problems in the loop. Which ever post type gets called for the first post on the page gets repeated for all the subsequent posts displayed. Am I missing a step? does the index.php need amending to allow posts of different types being displayed?

**Comment by SimonPadbury** [comment]
Hi Liam,

[Read this email on GitHub, so that you can see the rendered markdown in this email.]

Thankyou -- I just made some changes to b4st that enables it to do what you want. 

(I also bumped up the version number to 1.9, and I removed the explanatory comment that was in `loops/content.php` -- because b4st doesn't work that way any more, and I should have updated that comment. I had not used or thought about Post Formats in a while, and some changed I made to b4st had "broken" them. All fixed now -- I think. Let me know if you find anything else that needs fixing. Plus, I have renamed the partial PHP files in the `loops/` folder, so that they make more sense (to me, at least).)

Now there are three places where you can customise the design of [WordPress Post Formats](http://codex.wordpress.org/Post_Formats) in b4st:

(1.) Even if you do nothing else, you can style using the Post Formats CSS classes: on the single post pages, there will be a `<body>` class specific to your Post Format (e.g. `single-format-aside`, `single-format-quote`).

(2.) You can change the partial index-post. The `index.php` (and author.php, and category.php) obtains its loop from `loops/index-loop.php`. And each [post or excerpt] within that loop is now **another** partial file, called `loops/index-post.php`.

To make your own specific design for (e.g. aside) **where they are displayed on** `index.php`, you simply copy/clone `loops/index-post.php` and rename it as `loops/index-post-aside.php` -- and redesign that.

(3.) You can change the partial single-post. The `single.php` obtains its content from `loops/single-post.php`.

To make your own specific design for (e.g. aside) single post, you simply copy/clone `loops/single-post.php` and rename it as `loops/single-post-aside.php` -- and redesign that.

Note: the partial `loops/single-post.php` has in it only the "main column content" of your single post. You still get the same sidebar, header, footer as always. If you wish your e.g. `loops/single-post-gallery.php` to be more radically different, then start by redesigning `single.php`. Imagine: moving the sidebar **into** the `loops/single-post.php` -- and then when you copy/clone it for `loops/single-post-gallery.php` you can delete the sidebar in there, enabling you to have a full-width gallery.

**Comment by liammday** [comment]
Simon,

Many thanks for such a prompt and thorough update! I will be experimenting with this new theme ASAP. I must say I have bounced between a few starter themes recently (underscores and understrap to name just a few) but keep coming back to yours due to its light-weight build and the fact it doesn't rely on the dependencies being bundled into the package.

Thanks!
