### ISSUE TITLE
second drop down menu doesnt work

### ISSUE THREAD

**Issue by kaplan512** [SimonPadbury/b4st#38]
Hello again ;-)
Just made second dropdown menu http://a-medic.tests1.enlight.studio/ and it doesn't appear, just 'shake' my site and that's all. I made a different id for dropdown, but I don't think it is the problem. Have you faced this issue before?

**Comment by SimonPadbury** [comment]
Hello Kaplan,

(My response here is using Markdown -- so, read it on GitHub.)

You are talking about 2 navbars (in header + in footer), on small devices (<768px).

Your header navbar is all OK.

The 'shake' is because, when you toggle the **footer** "navbar-toggler", it is causing the **header** navbar to open!

Your footer navbar needs to be totally "navbarNavDropdown**1**" –– so, you need to correct the `<button>`. Make your footer narbar have this:

```
...
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown1" aria-controls="navbarNavDropdown1" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarNavDropdown1">
...
```

Bonus:

You have **two** Font Awesome being called (old version 4.7.0 CSS and new version 5.0.2 JS). Go into the enqueues and **delete** the style 'register & enqueue' for Cloudflare Font Awesome 4.7.0. 

Enjoy!

Simon

**Comment by kaplan512** [comment]
thank you
