### ISSUE TITLE
scrollspy.js compatibility with Wordpress

### ISSUE THREAD

**Issue by liammday** [SimonPadbury/b4st#45]
I've been trying to implement the Bootstrap scrollspy.js into custom menu items with a myurl.com/#anchor url within the page with little success. I've kept the full URL to allow the menu item to function on other pages.

I had to remove the function that applied the active class to the current page so as not to highlight all the anchor links within the current page (with the aim of selectively retargeting the current page using the WP standard current page class and a body.currentpage hierarchy).

I can't seem to identify the correct way to implement the data-attributes or the JS. The classes and IDs all seem to be in the correct position.

In line with your theme aims I believe this would serve as a suitable addition to the template seeing as one page themes are becoming ever more popular.

Thanks,

**Comment by liammday** [comment]
So I've got the scrollspy to work by making sure the ID being targeted for the nav is the <ul> being generated my the wp_nav_menu. The data attribute is set on the body still.

New problem - how to make the scrollspy detect links using a full URL not just an anchor? I'm thinking something that strips everything before the # when the URL matches the current page only?

**Comment by liammday** [comment]
`		if (window.location.pathname !== "/") {
    // Selector for top nav a elements
    $('#navbar a').each( function() {
        if (this.hash.indexOf('#') === 0) {
            // Alert this to an absolute link (pointing to the correct section on the hompage)
            this.href = "/" + this.hash;
        }
    });
}`

**Comment by liammday** [comment]
Working with this combination currently - only issue is on every page load other than the first time (or after a cache wipe) the offset doesn't work for the scrollspy, but still for the easing.

`$('body').scrollspy({
			target: '#navbar',
			offset: 80,
		});

		// jQuery for page scrolling feature - requires jQuery Easing plugin
		
		$('.page-scroll a').bind('click', function (event) {
			var $anchor = $(this);
			$('html, body').stop().animate({
				scrollTop: ($($anchor.attr('href')).offset().top - 80)
			}, 1250, 'easeInOutExpo');
			event.preventDefault();
		});

		// Wordpress anchor link hack

		if (window.location.pathname !== "/") {
			// Selector for top nav a elements
			$('#navbar a').each(function () {
				if (this.hash.indexOf('#') === 0) {
					// Alert this to an absolute link (pointing to the correct section on the hompage)
					this.href = "/" + this.hash;
				}
			});
		}`

**Comment by SimonPadbury** [comment]
Hi Liam,

Sorry for the delay, I've been busy.

Is this useful to you? https://www.jqueryscript.net/menu/jQuery-Plugin-Fixed-Bootstrap-4-Nav-Smooth-Scroll-navbar-fixed-js.html

**Comment by SimonPadbury** [comment]
Hi Liam,

You only need this: https://codepen.io/MOgorodnik/pen/AXwQmY?editors=1000 -- scroll down to see the jQuery script within the HTML.

But I modified it, a little. And see also the my notes below.

```
$('#scrollspy-test').scrollspy({ target: '#navbar-scrollspy' });   

$('#navbar-scrollspy a').on('click', function(event) {
	if (this.hash !== '') {
		event.preventDefault();

		var hash = this.hash;

		$('html, body').animate({
			scrollTop: $(hash).offset().top;
		}, 800, function() {
			window.location.hash = hash;
		});
	} 
});
```

1. Add this script above within a jQuery document ready function (e.g. the one in `b4st.js`). The top line of the script above is for Bootstrap 4 (Note: no `offset` – see https://getbootstrap.com/docs/4.0/components/scrollspy/#via-javascript).

2. And create a scrollspy test wrapper DIV with `id="scrollspy-test"` and in CSS give it `#scrollspy-test { position: relative}`. Within the test wrapper DIV, add some test panels, each with their own  `id=your-first-id` etc. (to the top, or to the wrapper). (Maybe copy the Bootstrap 4 docs and add a lot of _Lorem ipsum_ within each test panel).

3. To the b4st navbar in file `header.php`, add CSS class `fixed-top` and ID `id="navbar-scrollspy"`.

4. In WordPress, `Appearance > Menus`, add Custom Links to your navbar. Delete the suggested `http://` prefix and simply use `#your-first-id` etc. 

5. You can figure out how to prevent the top of your scrolling panels from being tucked under the fixed navbar, using some CSS.

6. When you've got this working, you can go anywhere. E.g. in place of your test panels, maybe set up a new, dedicated widget area, so that you can more easily create panels inside a series of text or raw html widgets. You with need to add `id=your-first-id` etc. (to the top, or to the wrapper) in each widget.
