### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by moz187** [SimonPadbury/b4st#55]
Hello Simon,

many thanks for this Starter. It's awesome!
Is it possible for you to coding a "Theme Options" in the next time?

greetz Moriz

**Comment by SimonPadbury** [comment]
Hello Moriz,

I have not thought to add Theme Options. Do you mean something for the Customizer? Or what do you have in mind?

Simon

**Comment by moz187** [comment]
yes for Customizer. Color Managment of the Theme. H1 h6 color and size. fonts and many more. The Logo about Customizer i have fix self. What do you think about?Mit freundlichen Grüßen / with best regardsMorizAm 24.04.2018 23:04 schrieb Simon Padbury <notifications@github.com>:Hello Moriz,

I have not thought to add Theme Options. Do you mean something for the Customizer? Or what do you have in mind?

Simon

**Comment by Jhynnifer** [comment]
Not going to lie, if this is meant to be a starter theme that you build off of, should it really have that much Customizer in it? One of the best things about B4ST over things like Understrap is that it's has base functionality and nothing more.

**Comment by SimonPadbury** [comment]
Hi Moriz and Jhynnifer,

Somebody asked me for WooCommerce support but I didn’t want to put it in b4st because it is intended as a starter theme. But I know some people never need WooCommerce. So I added a tutorial for it, at https://github.com/SimonPadbury/b4st/wiki/Adding-WooCommerce-support-to-a-b4st-child-theme <https://github.com/SimonPadbury/b4st/wiki/Adding-WooCommerce-support-to-a-b4st-child-theme> 

Maybe the place for “adding Costomizer support to b4st” is in a tutorial in the wiki.

Ideally, I want b4st to have only the basics in it – and nothing that people need to delete if they don’t want it.

Best regards,

Simon

**Comment by Jhynnifer** [comment]
Thanks, Simon... it's really what I absolutely love about this as a base theme! Keep up the awesome work!

**Comment by wcataldo** [comment]
Just want to pop in here and say thank you for your hard work Simon. That being said the first idea I had for quick customization's would be to simply give option to enque different bootswatch versions of bootstrap.

https://bootswatch.com/

to keep b4st light and breezey there is a cdn
https://www.bootstrapcdn.com/bootswatch/

Many thanks for your work again Simon.

**Comment by SimonPadbury** [comment]
Hi wcataldo,

It would be easy for anyone to swap in a Bootstwatch stylesheet by editing one line of code in the enqueues file. Or they could do it in a child theme, by deregistering the Bootstrap CSS and then (re) registering a Bootswatch of their choice. I could write a small wiki tutorial for that – or you dan do so if you like.

I already wrote a long tutorial for Boostrap SCSS customization.

https://github.com/SimonPadbury/b4st/wiki/Customizing-Bootstrap-4-(SCSS)-in-b4st 

(I don't think there is a Bootstrap 4 customizer anywhere.)
